name: Release Builder

on:
  release:
    types: [published]

jobs:
  macos-build:
    runs-on: macos-15-intel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.dmg
          path: dist/OnTheSpot.dmg

      - name: Upload to Release (macOS)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.dmg
          asset_name: OnTheSpot-x86_64.dmg
          asset_content_type: application/x-apple-diskimage

  macos-arm64-build:
    runs-on: macos-15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-arm64.dmg
          path: dist/OnTheSpot.dmg

      - name: Upload to Release (macOS)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.dmg
          asset_name: OnTheSpot-arm64.dmg
          asset_content_type: application/x-apple-diskimage
